spring:
  application: 
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaemperor/springcloud # prefix
          search-paths: config #相对路径
          
    
server: 
  context-path: /
  port: 4000
  
  